[terminal]
vt = 1

[default_session]
command = "sh -c 'export XDG_RUNTIME_DIR=/run/user/$(id -u); mkdir -p -m 0700 \"$XDG_RUNTIME_DIR\"; export WLR_NO_HARDWARE_CURSORS=1; exec cage -s -m extend -- /usr/bin/athanor-shell-rs --greeter'"
user = "greeter"

