# 🦅 Ermete OS - Starship Base Config
# Modern, minimal, and blazing fast.

format = """
[╭─](bold blue)$os$username$hostname$directory$git_branch$git_status$rust$nodejs$python
[╰─](bold blue)$character
"""

[os]
disabled = false
format = "[$symbol]($style)"
style = "bold blue"

[os.symbols]
Fedora = " "
Arch = " "
Macos = " "
Linux = " "

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "at [$hostname](bold red) in "

[directory]
style = "cyan"
read_only = " "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[rust]
symbol = " "
format = "via [$symbol$version]($style) "

[nodejs]
symbol = " "
format = "via [$symbol$version]($style) "

[python]
symbol = " "
format = "via [$symbol$version]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"
