[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

[[customizations.user]]
name = "hermes"
password = "$6$GfdUxvRhm3.l9uQ1$ffvfvawcJB91AU4HW7ul8LfD5GhSnUOQS1FSSOr/D6gG3FrtisMaGSxk0By6LFH9zBKiMJ.uwJtS40kG4ucZB0"
groups = ["wheel"]
