[colors]
# Sfondo semi-trasparente per l'effetto Glassmorphism
background=1e1e2ecc
text=cdd6f4ff
# Colore accento allineato a quello di Niri (#7fc8ff)
match=7fc8ffff
selection=313244cc
selection-text=cdd6f4ff
selection-match=7fc8ffff
border=7fc8ffff
