[main]
font=JetBrains Mono:size=14
dpi-aware=yes
icon-theme=Papirus-Dark
terminal=foot -e
prompt="❯ "
layer=overlay
lines=10
width=40
horizontal-pad=20
vertical-pad=20
inner-pad=10
image-size-ratio=0.5

[colors]
# Sfondo semi-trasparente per l'effetto Glassmorphism
background=1e1e2ecc
text=cdd6f4ff
# Colore accento allineato a quello di Niri (#7fc8ff)
match=7fc8ffff
selection=313244cc
selection-text=cdd6f4ff
selection-match=7fc8ffff
border=7fc8ffff

[border]
width=2
radius=12
