[package]
name = "athanor-oobe"
version = "0.1.0"
edition = "2021"
description = "Athanor OS Out-Of-Box Experience Wizard"
authors = ["Athanor Architect <architect@athanor.os>"]

[dependencies]
gtk4 = { workspace = true }
relm4 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
athanor-style = { path = "../athanor-style" }
tracing = { workspace = true }

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
