[package]
name = "athanor-mdm-rs"
version = "1.0.0"
edition = "2021"
description = "Athanor OS Mobile Device Management (Anti-Theft & Remote Wipe)"

[dependencies]
mimalloc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
athanor-bus-api = { path = "../../../../system/athanor-bus-api" }
libc = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }




[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
