[package]
name = "xdg-desktop-portal-athanor"
version = "1.0.0"
edition = "2021"
description = "Athanor OS Desktop Portal (Privacy, Screenshare, File Picker)"

[dependencies]
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }




[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
