[package]
name = "athanor-doctor"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true, features = ["tokio"] }
libc = { workspace = true }


[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
