[package]
name = "athanor-gatekeeper-rs"
version = "1.0.0"
edition = "2021"

[lib]
name = "athanor_gatekeeper_rs"
path = "src/lib.rs"

[[bin]]
name = "athanor-gatekeeper-rs"
path = "src/main.rs"

[dependencies]
libc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
athanor-bus-api = { path = "../../../../system/athanor-bus-api" }
xattr = "1.0"
pqc_dilithium = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
zeroize = { workspace = true, features = ["zeroize_derive"] }
subtle = { workspace = true }



[features]
default = ["std"]
std = []
scudo_ffi = []

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
