[package]
name = "athanor-ai-daemon"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
candle-core = "0.8"
candle-nn = "0.8"
vulkano = "0.34"
openvino = { version = "0.8", features = ["runtime-linking"] }
libc = { workspace = true }




[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
