[package]
name = "athanor-hypervisor-daemon"
version = "1.0.0"
edition = "2021"
description = "Athanor OS Zero-Trust Hardware Micro-Hypervisor & Confidential Enclave Orchestrator"
authors = ["athanor-security-architect"]

[dependencies]
anyhow = { workspace = true }
log = "0.4"
env_logger = { workspace = true }
nix = { workspace = true, features = ["fs", "ioctl", "process", "signal", "user"] }
libc = { workspace = true }
ring = "0.17"
sha2 = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
athanor-bus-api = { path = "../athanor-bus-api" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
vmm-sys-util = "0.12"
pqc_dilithium = { workspace = true }
tempfile = "3.27.0"

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"

