[package]
name = "athanor-recovery"
version = "1.0.0"
edition = "2021"
authors = ["Athanor Forge <forge@athanor.os>"]
description = "Pre-Boot GUI Recovery Kiosk & Rollback Manager for Athanor OS"
license = "MIT"

[[bin]]
name = "athanor-recovery-ui"
path = "src/main.rs"

[dependencies]
gtk4 = { workspace = true }
relm4 = { workspace = true }
glib = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true, features = ["tokio"] }
libc = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
anyhow = { workspace = true }
athanor-style = { path = "../../../../system/athanor-style" }
zeroize = { workspace = true, features = ["zeroize_derive"] }
subtle = { workspace = true }


[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
