[package]
name = "athanor-ebpf-sched"
version = "0.1.0"
edition = "2021"
description = "AI-Driven eBPF Kernel Scheduler Bridge (sched_ext & cgroup priority manager)"
build = "build.rs"


[dependencies]
tokio = { workspace = true, features = ["full", "signal", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
zbus = { workspace = true }
athanor-bus-api = { path = "../athanor-bus-api" }
libc = { workspace = true }
aya = { workspace = true }

candle-core = "0.8.0"

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"

