## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# Generated by rust2rpm 28
%bcond check 1

%global crate bat

%global debug_package %{nil}
Name:           rust-bat
Version:        0.26.1
Release:        %autorelease
Summary:        Cat(1) clone with wings

# * bat crate: MIT OR Apache-2.0
# * bundled content: Apache-2.0, BSD-2-Clause, BSD-2-Clause-Views, BSD-3-Clause, CC-BY-SA-3.0, MIT, Unlicense, WTFPL, UltraPermissive
License:        (MIT OR Apache-2.0) AND Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND CC-BY-SA-3.0 AND MIT AND Unlicense AND WTFPL AND LicenseRef-Fedora-UltraPermissive
URL:            https://crates.io/crates/bat
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          bat-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
# * port from path_abs to path-absolutize:
#   https://github.com/sharkdp/bat/pull/1025
# * adapt license tag to reflect bundled content
# * drop unused lessopen feature and its dependencies
Patch:          bat-fix-metadata.diff
# * port from path_abs to path-absolutize:
#   https://github.com/sharkdp/bat/pull/1025
Patch10:        0001-port-from-path_abs-to-path-absolutize.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A cat(1) clone with wings.}

%global _bundled_deps %{expand:
# Sublime Text 3 language definitions for syntax highlighting
# from: https://github.com/sublimehq/Packages/tree/759d6ee
# - all except Rust: LicenseRef-Fedora-UltraPermissive
#   https://gitlab.com/fedora/legal/fedora-license-data/-/issues/516
# - Rust: MIT
Provides:       bundled(sublime-syntax) = 4075~git759d6ee

# third-party language definitions for syntax highlighting
# AWK: MIT
Provides:       bundled(sublime-syntax-AWK)
# Ada: MIT
Provides:       bundled(sublime-syntax-Ada)
# Apache: BSD-2-Clause-Views
Provides:       bundled(sublime-syntax-Apache)
# AsciiDoc: MIT
Provides:       bundled(sublime-syntax-AsciiDoc)
# CMake: MIT
Provides:       bundled(sublime-syntax-CMake)
# CoffeeScript: MIT
Provides:       bundled(sublime-syntax-CoffeeScript)
# Crontab: MIT
Provides:       bundled(sublime-syntax-Crontab)
# Crontab/cron_descriptor: MIT
Provides:       bundled(sublime-syntax-Crontab-cron_descriptor)
# Crystal: Apache-2.0
Provides:       bundled(sublime-syntax-Crystal)
# Dart: MIT
Provides:       bundled(sublime-syntax-Dart)
# Docker: MIT
Provides:       bundled(sublime-syntax-Docker)
# DotENV: MIT
Provides:       bundled(sublime-syntax-DotENV)
# Elixir: MIT
Provides:       bundled(sublime-syntax-Elixir)
# Elm: MIT
Provides:       bundled(sublime-syntax-Elm)
# Email: MIT
Provides:       bundled(sublime-syntax-Email)
# Fish: MIT
Provides:       bundled(sublime-syntax-Fish)
# GLSL: Unlicense
Provides:       bundled(sublime-syntax-GLSL)
# GraphQL: WTFPL
Provides:       bundled(sublime-syntax-GraphQL)
# Groff: MIT
Provides:       bundled(sublime-syntax-Groff)
# HTML (Twig): BSD-3-Clause
Provides:       bundled(sublime-syntax-HTML-Twig)
# JavaScript (Babel): MIT
Provides:       bundled(sublime-syntax-JavaScript-Babel)
# Jsonnet: Apache-2.0
Provides:       bundled(sublime-syntax-Jsonnet)
# Julia: MIT
Provides:       bundled(sublime-syntax-Julia)
# Kotlin: Apache-2.0
Provides:       bundled(sublime-syntax-Kotlin)
# LLVM: MIT
Provides:       bundled(sublime-syntax-LLVM)
# Lean: Apache-2.0
Provides:       bundled(sublime-syntax-Lean)
# LiveScript: MIT
Provides:       bundled(sublime-syntax-LiveScript)
# MediaWiki: MIT
Provides:       bundled(sublime-syntax-MediaWiki)
# NSIS: Apache-2.0
Provides:       bundled(sublime-syntax-NSIS)
# Nginx: MIT
Provides:       bundled(sublime-syntax-Nginx)
# Ninja: MIT
Provides:       bundled(sublime-syntax-Ninja)
# Nix: MIT
Provides:       bundled(sublime-syntax-Nix)
# Org mode: BSD-2-Clause
Provides:       bundled(sublime-syntax-Org-mode)
# PowerShell: MIT
Provides:       bundled(sublime-syntax-PowerShell)
# Protobuf: MIT
Provides:       bundled(sublime-syntax-Protobuf)
# Puppet: MIT
Provides:       bundled(sublime-syntax-Puppet)
# PureScript: MIT AND Unlicense
Provides:       bundled(sublime-syntax-PureScript)
# QML: MIT
Provides:       bundled(sublime-syntax-QML)
# Robot: MIT
Provides:       bundled(sublime-syntax-Robot)
# SCSS_Sass: MIT
Provides:       bundled(sublime-syntax-SCSS_Sass)
# SLS: Apache-2.0
Provides:       bundled(sublime-syntax-SLS)
# Slim: MIT
Provides:       bundled(sublime-syntax-Slim)
# Stylus: MIT
Provides:       bundled(sublime-syntax-Stylus)
# SublimeEthereum: MIT
Provides:       bundled(sublime-syntax-SublimeEthereum)
# Svelte: MIT
Provides:       bundled(sublime-syntax-Svelte)
# Swift: MIT
Provides:       bundled(sublime-syntax-Swift)
# SystemVerilog: MIT
Provides:       bundled(sublime-syntax-SystemVerilog)
# TOML: MIT
Provides:       bundled(sublime-syntax-TOML)
# Terraform: MIT
Provides:       bundled(sublime-syntax-Terraform)
# TypeScript: MIT
Provides:       bundled(sublime-syntax-TypeScript)
# VimL: MIT
Provides:       bundled(sublime-syntax-VimL)
# Vue: MIT
Provides:       bundled(sublime-syntax-Vue)
# Zig: MIT
Provides:       bundled(sublime-syntax-Zig)
# cmd-help: MIT
Provides:       bundled(sublime-syntax-cmd-help)
# gnuplot: MIT
Provides:       bundled(sublime-syntax-gnuplot)
# hosts: MIT
Provides:       bundled(sublime-syntax-hosts)
# http-request-response: MIT
Provides:       bundled(sublime-syntax-http-request-response)
# varlink: MIT
Provides:       bundled(sublime-syntax-varlink)
# vscode-wgsl: MIT
Provides:       bundled(sublime-syntax-vscode-wgsl)

# third-party themes for syntax highlighting
# 1337-Scheme: MIT
Provides:       bundled(sublime-theme-1337-Scheme)
# Coldark: MIT
Provides:       bundled(sublime-theme-Coldark)
# DarkNeon: CC-BY-SA-3.0
Provides:       bundled(sublime-theme-DarkNeon)
# Nord-sublime: MIT, https://github.com/sharkdp/bat/issues/2987
Provides:       bundled(sublime-theme-Nord-sublime)
# Solarized: MIT
Provides:       bundled(sublime-theme-Solarized)
# TwoDark: MIT
Provides:       bundled(sublime-theme-TwoDark)
# dracula-sublime: MIT
Provides:       bundled(sublime-theme-dracula-sublime)
# github-sublime-theme: https://github.com/sharkdp/bat/issues/2984
Provides:       bundled(sublime-theme-github-sublime-theme)
# gruvbox: MIT
Provides:       bundled(sublime-theme-gruvbox)
# onehalf: MIT
Provides:       bundled(sublime-theme-onehalf)
# sublime-monokai-extended: MIT
Provides:       bundled(sublime-theme-sublime-monokai-extended)
# sublime-snazzy: https://github.com/sharkdp/bat/issues/2985
Provides:       bundled(sublime-theme-sublime-snazzy)
# visual-studio-dark-plus: https://github.com/sharkdp/bat/issues/2986
Provides:       bundled(sublime-theme-visual-studio-dark-plus)
# zenburn: BSD-2-Clause-Views
Provides:       bundled(sublime-theme-zenburn)
}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%{_bundled_deps}

# (Apache-2.0 OR MIT) AND BSD-3-Clause
# (MIT OR Apache-2.0) AND Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND CC-BY-SA-3.0 AND MIT AND Unlicense AND WTFPL
# (MIT OR Apache-2.0) AND BSD-3-Clause AND GPL-2.0-only WITH GCC-exception-2.0 AND MIT
# (MIT OR Apache-2.0) AND Unicode-DFS-2016
# 0BSD OR MIT OR Apache-2.0
# Apache-2.0
# Apache-2.0 OR BSL-1.0
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause
# LGPL-3.0-or-later
# MIT
# MIT OR Apache-2.0
# MIT OR Zlib OR Apache-2.0
# Unicode-3.0
# Unlicense OR MIT
# Zlib OR Apache-2.0 OR MIT
License:        Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND CC-BY-SA-3.0 AND LGPL-3.0-or-later AND GPL-2.0-only WITH GCC-exception-2.0 AND MIT AND Unicode-3.0 AND Unicode-DFS-2016 AND Unlicense AND WTFPL AND (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (MIT OR Apache-2.0 OR Zlib) AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%license NOTICE
%license LICENSE.dependencies
%{_bindir}/bat
%{bash_completions_dir}/bat.bash
%{fish_completions_dir}/bat.fish
%{zsh_completions_dir}/_bat
%{_mandir}/man1/bat.1*

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%{_bundled_deps}

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/NOTICE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+application-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+application-devel %{_description}

This package contains library source intended for building other packages which
use the "application" feature of the "%{crate}" crate.

%files       -n %{name}+application-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bugreport-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bugreport-devel %{_description}

This package contains library source intended for building other packages which
use the "bugreport" feature of the "%{crate}" crate.

%files       -n %{name}+bugreport-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-assets-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-assets-devel %{_description}

This package contains library source intended for building other packages which
use the "build-assets" feature of the "%{crate}" crate.

%files       -n %{name}+build-assets-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+clap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages which
use the "clap" feature of the "%{crate}" crate.

%files       -n %{name}+clap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+etcetera-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+etcetera-devel %{_description}

This package contains library source intended for building other packages which
use the "etcetera" feature of the "%{crate}" crate.

%files       -n %{name}+etcetera-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+git-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+git-devel %{_description}

This package contains library source intended for building other packages which
use the "git" feature of the "%{crate}" crate.

%files       -n %{name}+git-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+git2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+git2-devel %{_description}

This package contains library source intended for building other packages which
use the "git2" feature of the "%{crate}" crate.

%files       -n %{name}+git2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+grep-cli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+grep-cli-devel %{_description}

This package contains library source intended for building other packages which
use the "grep-cli" feature of the "%{crate}" crate.

%files       -n %{name}+grep-cli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+minimal-application-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+minimal-application-devel %{_description}

This package contains library source intended for building other packages which
use the "minimal-application" feature of the "%{crate}" crate.

%files       -n %{name}+minimal-application-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+minus-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+minus-devel %{_description}

This package contains library source intended for building other packages which
use the "minus" feature of the "%{crate}" crate.

%files       -n %{name}+minus-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+paging-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+paging-devel %{_description}

This package contains library source intended for building other packages which
use the "paging" feature of the "%{crate}" crate.

%files       -n %{name}+paging-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+regex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-devel %{_description}

This package contains library source intended for building other packages which
use the "regex" feature of the "%{crate}" crate.

%files       -n %{name}+regex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+regex-fancy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-fancy-devel %{_description}

This package contains library source intended for building other packages which
use the "regex-fancy" feature of the "%{crate}" crate.

%files       -n %{name}+regex-fancy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+regex-onig-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-onig-devel %{_description}

This package contains library source intended for building other packages which
use the "regex-onig" feature of the "%{crate}" crate.

%files       -n %{name}+regex-onig-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+shell-words-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+shell-words-devel %{_description}

This package contains library source intended for building other packages which
use the "shell-words" feature of the "%{crate}" crate.

%files       -n %{name}+shell-words-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+walkdir-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+walkdir-devel %{_description}

This package contains library source intended for building other packages which
use the "walkdir" feature of the "%{crate}" crate.

%files       -n %{name}+walkdir-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wild-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wild-devel %{_description}

This package contains library source intended for building other packages which
use the "wild" feature of the "%{crate}" crate.

%files       -n %{name}+wild-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
# install man page
find target/release/build -name bat.1 -print -quit | xargs -I {} install -Dpm0644 {} %{buildroot}/%{_mandir}/man1/bat.1
# install shell completions
find target/release/build -name bat.bash -print -quit | xargs -I {} install -Dpm0644 {} %{buildroot}/%{bash_completions_dir}/bat.bash
find target/release/build -name bat.fish -print -quit | xargs -I {} install -Dpm0644 {} %{buildroot}/%{fish_completions_dir}/bat.fish
find target/release/build -name bat.zsh -print -quit | xargs -I {} install -Dpm0644 {} %{buildroot}/%{zsh_completions_dir}/_bat

%if %{with check}
%check
%cargo_test
%endif

%changelog
## START: Generated by rpmautospec
* Mon Mar 23 2026 blinxen <h-k-81@hotmail.com> - 0.26.1-1
- Update to version 0.26.1 (rhbz#2405016)

* Sat Feb 07 2026 Fabio Valentini <decathorpe@gmail.com> - 0.25.0-9
- Rebuild for RUSTSEC-2026-{0007,0008,0009} and CVE-2026-25537

* Sat Feb 07 2026 Fabio Valentini <decathorpe@gmail.com> - 0.25.0-8
- Bump git2 dependency to v0.20

* Sat Jan 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 0.25.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Fri Oct 31 2025 Benjamin A. Beasley <code@musicinmybrain.net> - 0.25.0-6
- Add the path-absolutize patch to rust2rpm.toml

* Fri Oct 31 2025 Benjamin A. Beasley <code@musicinmybrain.net> - 0.25.0-5
- Allow etcetera 0.11

* Sat Jul 26 2025 Benjamin A. Beasley <code@musicinmybrain.net> - 0.25.0-4
- Allow console 0.16

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.25.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Thu Apr 24 2025 Benjamin A. Beasley <code@musicinmybrain.net> - 0.25.0-2
- Update etcetera dependency to version 0.10
- Update License based on other indirect dependency changes

* Tue Jan 28 2025 blinxen <h-k-81@hotmail.com> - 0.25.0-1
- Update to version 0.25.0 (rhbz#2336226)

* Sun Jan 19 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.24.0-12
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Tue Oct 29 2024 Fabio Valentini <decathorpe@gmail.com> - 0.24.0-11
- Bump git2 dependency from 0.18 to 0.19

* Wed Oct 23 2024 Fabio Valentini <decathorpe@gmail.com> - 0.24.0-10
- Fix port to nix 0.29

* Wed Oct 23 2024 Fabio Valentini <decathorpe@gmail.com> - 0.24.0-9
- Bump nix dev-dependency from 0.26.2 to 0.29

* Wed Oct 23 2024 Fabio Valentini <decathorpe@gmail.com> - 0.24.0-8
- Drop unused lessopen feature and its dependencies

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.24.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Sun Jun 02 2024 Fabio Valentini <decathorpe@gmail.com> - 0.24.0-6
- Adapt license tags, document bundled Sublime Text grammars and themes

* Thu May 23 2024 Fabio Valentini <decathorpe@gmail.com> - 0.24.0-5
- Rebuild with Rust 1.78 to fix incomplete debuginfo and backtraces

* Thu Mar 07 2024 Michel Lind <salimma@fedoraproject.org> - 0.24.0-4
- Rebuilt for nu-ansi-term 0.50.0

* Tue Feb 13 2024 Fabio Valentini <decathorpe@gmail.com> - 0.24.0-3
- Rebuild for CVE-2024-24575 and CVE-2024-24577 in libgit2

* Fri Jan 26 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.24.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Sun Oct 29 2023 Michel Lind <salimma@fedoraproject.org> - 0.24.0-1
- Update to 0.24.0

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.23.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Sat Jul 15 2023 Fabio Valentini <decathorpe@gmail.com> - 0.23.0-1
- Update to version 0.23.0; Fixes RHBZ#2124711

* Sat Jan 28 2023 Fabio Valentini <decathorpe@gmail.com> - 0.21.0-6
- Rebuild for CVE-2022-24765 and CVE-2022-29187 in libgit2

* Fri Jan 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.21.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Wed Dec 21 2022 Fabio Valentini <decathorpe@gmail.com> - 0.21.0-4
- Disable doctests on ppc64le to work around a compiler crash on LLVM 15

* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.21.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jul 21 2022 Fabio Valentini <decathorpe@gmail.com> - 0.21.0-2
- Disable doctests on armv7hl to work around a compiler crash on LLVM 14

* Thu Jul 21 2022 Fabio Valentini <decathorpe@gmail.com> - 0.21.0-1
- Update to version 0.21.0; Fixes RHBZ#2038592

* Wed Feb 16 2022 Maxwell G <gotmax@e.email> - 0.18.3-5
- Add missing shell completions

* Tue Feb 15 2022 Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl> - 0.18.3-4
- Rebuild with package notes

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.18.3-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Sun Nov 28 2021 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.18.3-2
- Rebuild for libgit2 1.3.x

* Sun Nov 14 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.18.3-1
- Bump assert_cmd to 2.0.0

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.17.1-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.17.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Dec 29 14:21:41 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.17.1-3
- Rebuild against libgit2 1.1.x

* Mon Dec 28 13:27:34 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.17.1-2
- Rebuild

* Sat Dec 12 2020 Fabio Valentini <decathorpe@gmail.com> - 0.17.1-1
- Update to version 0.17.1.
- Remove features with missing dependencies (regex-fancy).
- Fixes RHBZ#1900814

* Tue Oct 27 2020 Fabio Valentini <decathorpe@gmail.com> - 0.16.0-1
- Update to version 0.16.0.

* Sun Aug 16 15:01:11 GMT 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.15.4-3
- Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.15.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Sun Jun 21 10:43:31 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.15.4-1
- Update to 0.15.4

* Mon May 25 18:52:24 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.15.2-1
- Update to 0.15.2

* Tue May 12 2020 Josh Stone <jistone@redhat.com> - 0.15.1-1
- Update to 0.15.1

* Sat May 02 10:58:34 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.15.0-2
- Update console to 0.11.2

* Mon Apr 27 08:12:43 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.15.0-1
- Update to 0.15.0

* Thu Apr 23 2020 Josh Stone <jistone@redhat.com> - 0.14.0-1
- Update to 0.14.0

* Wed Apr 15 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.13.0-2
- Rebuild for libgit2 1.0.0

* Sun Mar 22 14:24:13 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.13.0-1
- Update to 0.13.0

* Thu Mar 19 11:31:13 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.12.1-5
- Update git2 to 0.13

* Tue Mar 03 2020 Josh Stone <jistone@redhat.com> - 0.12.1-4
- Bump git2 to 0.12

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.12.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Wed Dec 25 09:50:18 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.12.1-2
- Bump git2 to 0.11

* Tue Dec 10 2019 Josh Stone <jistone@redhat.com> - 0.12.1-1
- Update to 0.12.1

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Jul 14 18:28:38 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.11.0-3
- Update dirs to 2.0

* Fri Jun 07 2019 Josh Stone <jistone@redhat.com> - 0.11.0-2
- Bump git2 to 0.9

* Sat Jun 01 2019 Josh Stone <jistone@redhat.com> - 0.11.0-1
- Update to 0.11.0

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.10.0-1
- Update to 0.10.0

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Nov 13 2018 Josh Stone <jistone@redhat.com> - 0.9.0-1
- Update to 0.9.0

* Sun Nov 04 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-1
- Update to 0.8.0

* Thu Oct 04 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.1-1
- Update to 0.7.1

* Thu Sep 13 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.0-1
- Update to 0.7.0

* Mon Sep 03 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.1-1
- Initial package

## END: Generated by rpmautospec
