[package]
name = "athanor-settings-rs"
version = "1.0.0"
edition = "2021"
authors = ["Athanor Forge <forge@athanor.os>"]
description = "Pure Rust native System Settings for Athanor OS"

[dependencies]
mimalloc = { workspace = true }
gtk4 = { workspace = true }
glib = { workspace = true }
zbus = { workspace = true }
tokio = { workspace = true, features = ["full"] }
rustix = { version = "0.38", features = ["process"] }
relm4 = { workspace = true }
anyhow = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
athanor-style = { path = "../../../../system/athanor-style" }
athanor-niri-ipc = { version = "0.1.0", path = "../../athanor-niri-ipc" }
athanor-bus-api = { path = "../../../../system/athanor-bus-api" }
pqc_dilithium = { workspace = true }





[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
