color={{colors.background.default.hex_stripped}}cc
inside-color={{colors.surface.default.hex_stripped}}80
ring-color={{colors.primary.default.hex_stripped}}
key-hl-color={{colors.tertiary.default.hex_stripped}}
line-color={{colors.surface_variant.default.hex_stripped}}00
text-color={{colors.on_surface.default.hex_stripped}}
inside-clear-color={{colors.surface.default.hex_stripped}}80
ring-clear-color={{colors.secondary.default.hex_stripped}}
inside-wrong-color={{colors.error.default.hex_stripped}}80
ring-wrong-color={{colors.error.default.hex_stripped}}
indicator-idle-visible=false
indicator-radius=80
indicator-thickness=6
