[package]
name = "athanor-mesh-sync"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
boringtun = "0.7"
x25519-dalek = "2.0.1"
base64 = "0.21"
rand_core = "0.6"
pqc_dilithium = { workspace = true }
athanor-bus-api = { path = "../../../../system/athanor-bus-api" }
rtnetlink = "0.14.1"
netlink-packet-route = "0.19.0"
defguard_wireguard_rs = "0.11.1"
futures = "0.3"

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"

