#![allow(unsafe_code)]
#![allow(unexpected_cfgs)]
//! Shared wire types and D-Bus proxy definitions used across the Athanor OS mesh/telemetry stack.
//!
//! This crate has two independent halves:
//! - Plain `serde`-serializable structs (`KernelTelemetry`, `MeshPeerInfo`,
//!   `NodeIdentityPayload`, `AiDecisionPayload`, `MeshBusStatusPayload`) that
//!   several daemons pass to each other as JSON over D-Bus method calls. They
//!   carry no logic; they exist so producers and consumers agree on a shape.
//! - [`shm_ring`]: a real zero-copy SPSC shared-memory ring buffer used for
//!   lower-latency IPC than D-Bus method calls allow (see that module's docs
//!   for the safety model of its `unsafe` code).
//! - [`socket`]: small framing types (`MeshPacketType`, `MeshSocketFrame`) for
//!   the mesh's raw socket protocol.
//! - [`polkit`]: the one polkit client (subject types, authority proxy, caller-authorization
//!   helpers) shared by every daemon that gates a D-Bus method behind an action id.
//!
//! Note: despite the crate name, this is a types/library crate, not a running
//! "bus API" service — it has no `main.rs` and produces no binary or daemon on
//! its own; it is consumed as a path dependency by the daemons that do.
use serde::{Deserialize, Serialize};
use zbus::proxy;

pub mod shm_ring;
pub use shm_ring::*;

pub mod socket;
pub mod polkit;

/// Common telemetry payload collected from Ring-0 eBPF probes.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct KernelTelemetry {
    pub timestamp_secs: u64,
    pub syscall_frequency_hz: u64,
    pub memory_pressure_mb: u64,
    pub network_passed_packets: u64,
    pub network_dropped_packets: u64,
    pub land_attacks_detected: u64,
    pub tcp_scans_detected: u64,
    pub blocklist_drops: u64,
    pub unauthorized_port_drops: u64,
}

/// Mesh peer metadata structure shared across services.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MeshPeerInfo {
    pub node_id: String,
    pub endpoint: Option<String>,
    pub virtual_ip: String,
    pub x25519_pk_b64: String,
    pub state: String,
    pub last_handshake: u64,
    pub packets_rx: u64,
    pub packets_tx: u64,
    pub latency_ms: u32,
    pub zero_trust_verified: bool,
}

/// Post-Quantum Node Identity payload structure.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct NodeIdentityPayload {
    pub node_id: String,
    pub x25519_public_b64: String,
}

/// AI Decision Payload returned by the NPU inference engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiDecisionPayload {
    pub anomaly_detected: bool,
    pub risk_score: f32,
    pub recommended_actions: Vec<String>,
    pub sysctl_mitigations: Vec<(String, String)>,
    pub block_ips: Vec<String>,
    pub zero_trust_enforce: bool,
}

/// High-level status payload for the PQC Mesh Bus.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MeshBusStatusPayload {
    pub node_id: String,
    pub status: String,
    pub active_peers: usize,
    pub zero_trust_enabled: bool,
}

/// Shared DBus interface proxy definition for org.athanor.MeshBus.
///
/// This is a client-side proxy trait only (generated by `#[proxy]`): it does
/// not implement the interface, it lets any daemon in the workspace call into
/// whichever process actually registers `org.athanor.MeshBus` on the system
/// bus (see `system/athanor-mesh-bus`).
#[proxy(
    interface = "org.athanor.MeshBus",
    default_service = "org.athanor.MeshBus",
    default_path = "/org/athanor/MeshBus"
)]
pub trait MeshBusInterface {
    /// Returns a human-readable status string for the mesh bus.
    async fn status(&self) -> zbus::Result<String>;
    /// Returns the current peer list as a JSON-encoded string.
    async fn get_peers(&self) -> zbus::Result<String>;
    /// Registers a new mesh peer by node ID, network endpoint, and base64-encoded X25519 public key.
    async fn add_peer(
        &self,
        node_id: String,
        endpoint: String,
        x25519_pk_b64: String,
    ) -> zbus::Result<String>;
    /// Removes a previously registered mesh peer by node ID.
    async fn remove_peer(&self, node_id: String) -> zbus::Result<String>;
    /// Initiates a handshake with a mesh peer at the given endpoint.
    async fn initiate_handshake(&self, node_id: String, endpoint: String) -> zbus::Result<String>;
}

