use serde::{Deserialize, Serialize};

/// IPC commands sent from AI daemon, Athanor Shell, or CLI tools to the compositor.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "command", content = "payload")]
pub enum AiLayoutCommand {
    /// Change the tiling layout mode (e.g. AI-driven, Master-Stack, Spiral, Grid).
    SetLayoutMode { mode: LayoutMode },
    /// Apply specific window coordinates & splits generated by AI agent.
    ApplyAiTileMap { window_placements: Vec<WindowPlacement> },
    /// Adjust inner and outer window padding gaps.
    SetGaps { inner: u32, outer: u32 },
    /// Focus a specific window by its numeric ID.
    FocusWindow { window_id: u64 },
    /// Request screen capture (invokes Gatekeeper DBus auth).
    RequestScreenCapture { app_id: String, pid: u32, output_id: u64 },
    /// Request global input grab (invokes Gatekeeper DBus auth).
    RequestGlobalInputGrab { app_id: String, pid: u32 },
    /// Query the current compositor state and active tiling layout.
    QueryState,
    /// Ping request for health check.
    Ping,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LayoutMode {
    AiDriven,
    MasterStack,
    Spiral,
    Grid,
    Floating,
}

impl std::fmt::Display for LayoutMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AiDriven => write!(f, "AI-Driven Dynamic"),
            Self::MasterStack => write!(f, "Master-Stack"),
            Self::Spiral => write!(f, "Spiral Fibonacci"),
            Self::Grid => write!(f, "Grid Matrix"),
            Self::Floating => write!(f, "Floating"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowPlacement {
    pub window_id: u64,
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
    pub workspace: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowInfo {
    pub id: u64,
    pub title: String,
    pub app_id: String,
    pub geometry: WindowPlacement,
    pub is_focused: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompositorStatus {
    pub active_mode: LayoutMode,
    pub window_count: usize,
    pub active_workspace: u32,
    pub drm_kms_active: bool,
    pub windows: Vec<WindowInfo>,
    pub inner_gap: u32,
    pub outer_gap: u32,
    pub active_screencopy_frames: usize,
    pub active_input_grabs: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IpcResponse {
    pub success: bool,
    pub message: String,
    pub status: Option<CompositorStatus>,
}

impl IpcResponse {
    pub fn success(message: impl Into<String>, status: Option<CompositorStatus>) -> Self {
        Self {
            success: true,
            message: message.into(),
            status,
        }
    }

    pub fn error(message: impl Into<String>) -> Self {
        Self {
            success: false,
            message: message.into(),
            status: None,
        }
    }
}
