[package]
name = "athanor-mesh-bus"
version = "1.0.0"
edition = "2021"
description = "Athanor OS Zero-Trust Post-Quantum Cryptography WireGuard P2P Mesh Bus Daemon"
authors = ["athanor-mesh-pqc-architect"]

[dependencies]
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
base64 = "0.21"
rand = { workspace = true }
rand_core = "0.6"
x25519-dalek = "2.0.1"
sha2 = { workspace = true }
ring = "0.17"
hex = { workspace = true }
athanor-bus-api = { path = "../athanor-bus-api" }
libc = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive"] }
subtle = { workspace = true }




[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"

