//! eBPF Trampoline Injector & Live Hot-Patcher Module for Athanor OS
//!
//! Provides Ring-0 kernel probe (`kprobe`), user-space probe (`uprobe`),
//! and BPF trampoline live function replacement (`freplace` / `Extension`)
//! injection and secure rollback capability using the Aya eBPF framework.

use anyhow::{anyhow, Context, Result};
use aya::programs::extension::{Extension, ExtensionLinkId};
use aya::programs::kprobe::{KProbe, KProbeLinkId};
use aya::programs::uprobe::{UProbe, UProbeLinkId};
use aya::programs::ProgramFd;
use aya::Ebpf;
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::Mutex;
use tracing::{error, info, warn};

/// Target parameter for `freplace` BPF Trampolines
#[derive(Debug, Clone)]
pub enum FReplaceTarget {
    /// Target program function name inside an already loaded eBPF program
    ProgramFunc {
        target_program_name: String,
        target_func_name: String,
    },
    /// Target program file descriptor handle
    ProgramFd {
        target_func_name: String,
    },
}

/// Type of eBPF hot patch to inject
#[derive(Debug, Clone)]
pub enum PatchType {
    /// Kernel probe attached to vulnerable kernel functions (e.g., `sys_execve`, `do_unlinkat`)
    KProbe {
        target_function: String,
        offset: u64,
    },
    /// User-space probe attached to shared libraries (e.g., `/usr/lib/libc.so.6`)
    UProbe {
        target_binary: String,
        symbol: String,
        pid: Option<i32>,
    },
    /// Live function replacement via BPF Trampolines (`freplace` / eBPF Extension)
    FReplace {
        target_func_name: String,
        target_program_name: Option<String>,
    },
}

/// Specification of a JIT-compiled eBPF hot patch artifact
#[derive(Debug, Clone)]
pub enum PatchSource {
    /// Raw eBPF ELF bytecode generated by the JIT Architect
    Bytecode(Vec<u8>),
    /// Path to compiled eBPF object file
    FilePath(String),
}

#[derive(Debug, Clone)]
pub struct PatchSpec {
    pub id: String,
    pub name: String,
    pub program_name: String,
    pub patch_type: PatchType,
    pub source: PatchSource,
}

/// Status of an injected hot patch
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PatchStatus {
    Applied,
    Detached,
    RolledBack(String),
    Failed(String),
}

/// Represents an active attached link for rollback tracking
enum ActiveLink {
    KProbe { link_id: KProbeLinkId },
    UProbe { link_id: UProbeLinkId },
    Extension { link_id: ExtensionLinkId },
}

/// Internal storage record for an active patch instance
struct ActivePatchRecord {
    spec: PatchSpec,
    status: PatchStatus,
    ebpf_instance: Option<Ebpf>,
    link: Option<ActiveLink>,
    error_count: u32,
    applied_timestamp_secs: u64,
}

/// BPF Trampoline Injector and Hot Patch Lifecycle Manager
pub struct BpfTrampolineInjector {
    patches: HashMap<String, ActivePatchRecord>,
}

impl BpfTrampolineInjector {
    /// Create a new instance of the BPF Trampoline Injector
    pub fn new() -> Self {
        info!("💉 [BPF Trampoline Injector] Initializing Ring-0 Hot-Patcher Engine...");
        Self {
            patches: HashMap::new(),
        }
    }

    /// Load eBPF bytecode and inject a `kprobe` patch onto a target kernel function
    pub fn inject_kprobe(
        &mut self,
        patch_id: &str,
        bytecode: &[u8],
        program_name: &str,
        target_function: &str,
        offset: u64,
    ) -> Result<()> {
        let spec = PatchSpec {
            id: patch_id.to_string(),
            name: format!("KProbe-Patch-{}", patch_id),
            program_name: program_name.to_string(),
            patch_type: PatchType::KProbe {
                target_function: target_function.to_string(),
                offset,
            },
            source: PatchSource::Bytecode(bytecode.to_vec()),
        };

        self.apply_patch(spec)
    }

    /// Load eBPF bytecode and inject a `uprobe` patch onto a target user-space symbol/library (e.g. `libc`)
    pub fn inject_uprobe(
        &mut self,
        patch_id: &str,
        bytecode: &[u8],
        program_name: &str,
        target_binary: &str,
        symbol: &str,
        pid: Option<i32>,
    ) -> Result<()> {
        let spec = PatchSpec {
            id: patch_id.to_string(),
            name: format!("UProbe-Patch-{}", patch_id),
            program_name: program_name.to_string(),
            patch_type: PatchType::UProbe {
                target_binary: target_binary.to_string(),
                symbol: symbol.to_string(),
                pid,
            },
            source: PatchSource::Bytecode(bytecode.to_vec()),
        };

        self.apply_patch(spec)
    }

    /// Load eBPF bytecode and perform live function replacement (`freplace`) via BPF trampolines
    pub fn inject_freplace(
        &mut self,
        patch_id: &str,
        bytecode: &[u8],
        program_name: &str,
        target_func_name: &str,
        target_program_name: Option<&str>,
    ) -> Result<()> {
        let spec = PatchSpec {
            id: patch_id.to_string(),
            name: format!("FReplace-Patch-{}", patch_id),
            program_name: program_name.to_string(),
            patch_type: PatchType::FReplace {
                target_func_name: target_func_name.to_string(),
                target_program_name: target_program_name.map(|s| s.to_string()),
            },
            source: PatchSource::Bytecode(bytecode.to_vec()),
        };

        self.apply_patch(spec)
    }

    /// Apply a hot patch according to its specification
    pub fn apply_patch(&mut self, spec: PatchSpec) -> Result<()> {
        let patch_id = &spec.id;

        if self.patches.contains_key(patch_id) {
            return Err(anyhow!("Patch ID '{}' is already registered/applied", patch_id));
        }

        info!(
            "💉 [BPF Trampoline Injector] Loading & Injecting Patch '{}' ({})",
            spec.id, spec.name
        );

        // Load eBPF ELF binary
        let load_result = match &spec.source {
            PatchSource::Bytecode(bytes) => Ebpf::load(bytes),
            PatchSource::FilePath(path) => Ebpf::load_file(path),
        };

        let now_secs = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        match load_result {
            Ok(mut ebpf) => {
                match &spec.patch_type {
                    PatchType::KProbe {
                        target_function,
                        offset,
                    } => {
                        let program: &mut KProbe = ebpf
                            .program_mut(&spec.program_name)
                            .ok_or_else(|| anyhow!("Program '{}' not found in eBPF binary", spec.program_name))?
                            .try_into()
                            .context("Failed to cast eBPF program to KProbe")?;

                        program.load().context("Failed to load KProbe program into kernel")?;
                        let link_id = program
                            .attach(target_function, *offset)
                            .context(format!("Failed to attach KProbe to kernel function '{}'", target_function))?;

                        info!(
                            "✅ [KProbe Attached] Patch '{}' successfully hooked into kernel function '{}' (+offset {})",
                            patch_id, target_function, offset
                        );

                        self.patches.insert(
                            spec.id.clone(),
                            ActivePatchRecord {
                                spec,
                                status: PatchStatus::Applied,
                                ebpf_instance: Some(ebpf),
                                link: Some(ActiveLink::KProbe { link_id }),
                                error_count: 0,
                                applied_timestamp_secs: now_secs,
                            },
                        );
                    }
                    PatchType::UProbe {
                        target_binary,
                        symbol,
                        pid,
                    } => {
                        let program: &mut UProbe = ebpf
                            .program_mut(&spec.program_name)
                            .ok_or_else(|| anyhow!("Program '{}' not found in eBPF binary", spec.program_name))?
                            .try_into()
                            .context("Failed to cast eBPF program to UProbe")?;

                        program.load().context("Failed to load UProbe program into kernel")?;
                        let link_id = program
                            .attach(Some(symbol), 0, target_binary, *pid)
                            .context(format!(
                                "Failed to attach UProbe to binary '{}' symbol '{}'",
                                target_binary, symbol
                            ))?;

                        info!(
                            "✅ [UProbe Attached] Patch '{}' successfully hooked into user-space binary '{}' symbol '{}'",
                            patch_id, target_binary, symbol
                        );

                        self.patches.insert(
                            spec.id.clone(),
                            ActivePatchRecord {
                                spec,
                                status: PatchStatus::Applied,
                                ebpf_instance: Some(ebpf),
                                link: Some(ActiveLink::UProbe { link_id }),
                                error_count: 0,
                                applied_timestamp_secs: now_secs,
                            },
                        );
                    }
                    PatchType::FReplace {
                        target_func_name,
                        target_program_name,
                    } => {
                        // For FReplace, resolve the target program's ProgramFd if specified
                        let target_prog_name = target_program_name.as_deref().unwrap_or("main");
                        let target_prog = ebpf
                            .program(target_prog_name)
                            .ok_or_else(|| anyhow!("Target program '{}' not found for freplace trampoline", target_prog_name))?;

                        let target_fd: ProgramFd = target_prog
                            .fd()
                            .context("Failed to retrieve target program file descriptor")?
                            .try_clone()
                            .context("Failed to clone target program file descriptor")?;

                        let program: &mut Extension = ebpf
                            .program_mut(&spec.program_name)
                            .ok_or_else(|| anyhow!("Program '{}' not found in eBPF binary", spec.program_name))?
                            .try_into()
                            .context("Failed to cast eBPF program to Extension/FReplace")?;

                        program
                            .load(target_fd, target_func_name)
                            .context("Failed to load FReplace extension program into kernel")?;

                        let link_id = program
                            .attach()
                            .context("Failed to attach BPF trampoline FReplace link")?;

                        info!(
                            "✅ [FReplace Trampoline Live-Swapped] Patch '{}' successfully replaced target function '{}' live via BPF Trampoline",
                            patch_id, target_func_name
                        );

                        self.patches.insert(
                            spec.id.clone(),
                            ActivePatchRecord {
                                spec,
                                status: PatchStatus::Applied,
                                ebpf_instance: Some(ebpf),
                                link: Some(ActiveLink::Extension { link_id }),
                                error_count: 0,
                                applied_timestamp_secs: now_secs,
                            },
                        );
                    }
                }
                Ok(())
            }
            Err(e) => {
                error!(
                    "🔥 [BPF Injector] CRITICAL: Real eBPF loader failed: {}. Zero-Trust enforcement prevents simulation fallback for patch '{}'",
                    e, patch_id
                );
                Err(anyhow::anyhow!("eBPF Ring-0 injection failed: {}", e))
            }
        }
    }

    /// Safely detach (rollback) a specific patch by ID
    pub fn rollback(&mut self, patch_id: &str) -> Result<()> {
        let record = self
            .patches
            .get_mut(patch_id)
            .ok_or_else(|| anyhow!("Patch ID '{}' not found for rollback", patch_id))?;

        if record.status == PatchStatus::Detached
            || matches!(record.status, PatchStatus::RolledBack(_))
        {
            info!("Patch '{}' is already detached/rolled back", patch_id);
            return Ok(());
        }

        info!(
            "🛡️ [Safe Rollback Triggered] Detaching patch '{}' ({}) from Ring-0...",
            patch_id, record.spec.name
        );

        let link = record.link.take();

        if let Some(ref mut ebpf) = record.ebpf_instance {
            if let Some(active_link) = link {
                match active_link {
                    ActiveLink::KProbe { link_id } => {
                        if let Some(prog) = ebpf.program_mut(&record.spec.program_name) {
                            if let Ok(kprobe) = <&mut KProbe>::try_from(prog) {
                                let _ = kprobe.detach(link_id);
                            }
                        }
                    }
                    ActiveLink::UProbe { link_id } => {
                        if let Some(prog) = ebpf.program_mut(&record.spec.program_name) {
                            if let Ok(uprobe) = <&mut UProbe>::try_from(prog) {
                                let _ = uprobe.detach(link_id);
                            }
                        }
                    }
                    ActiveLink::Extension { link_id } => {
                        if let Some(prog) = ebpf.program_mut(&record.spec.program_name) {
                            if let Ok(ext) = <&mut Extension>::try_from(prog) {
                                let _ = ext.detach(link_id);
                            }
                        }
                    }
                }
            }
        }

        record.status = PatchStatus::RolledBack("Manual or automated instability rollback".to_string());
        info!("✅ [Rollback Complete] Patch '{}' safely unhooked.", patch_id);
        Ok(())
    }

    /// Rollback all currently active patches in emergency mode
    pub fn rollback_all(&mut self) -> Result<usize> {
        info!("🚨 [EMERGENCY ROLLBACK] Rolling back all active eBPF hot patches...");
        let keys: Vec<String> = self.patches.keys().cloned().collect();
        let mut count = 0;
        for id in keys {
            if self.rollback(&id).is_ok() {
                count += 1;
            }
        }
        info!("✅ Total patches rolled back: {}", count);
        Ok(count)
    }

    /// Record an instability error event associated with a patch
    pub fn report_patch_error(&mut self, patch_id: &str, error_msg: &str) {
        if let Some(record) = self.patches.get_mut(patch_id) {
            record.error_count += 1;
            warn!(
                "⚠️ Patch '{}' instability reported: {}. Total errors: {}",
                patch_id, error_msg, record.error_count
            );
        }
    }

    /// Audit active patches and automatically trigger rollback if error threshold is exceeded
    pub fn auto_health_audit(&mut self, max_allowed_errors: u32) -> Vec<String> {
        let mut rolled_back = Vec::new();
        let keys: Vec<String> = self.patches.keys().cloned().collect();

        for id in keys {
            if let Some(record) = self.patches.get(&id) {
                if record.status == PatchStatus::Applied && record.error_count >= max_allowed_errors {
                    error!(
                        "🔥 Patch '{}' exceeded instability threshold ({} >= {}). Executing auto-rollback!",
                        id, record.error_count, max_allowed_errors
                    );
                    rolled_back.push(id.clone());
                }
            }
        }

        for id in &rolled_back {
            let _ = self.rollback(id);
        }

        rolled_back
    }

    /// List all patches and their current statuses
    pub fn list_patches(&self) -> Vec<(String, String, PatchStatus, u32, u64)> {
        self.patches
            .values()
            .map(|r| (r.spec.id.clone(), r.spec.name.clone(), r.status.clone(), r.error_count, r.applied_timestamp_secs))
            .collect()
    }
}

/// Shared Thread-Safe Hot-Patcher Handle
#[derive(Clone)]
pub struct SharedHotPatcher {
    inner: Arc<Mutex<BpfTrampolineInjector>>,
}

impl SharedHotPatcher {
    pub fn new() -> Self {
        Self {
            inner: Arc::new(Mutex::new(BpfTrampolineInjector::new())),
        }
    }
}

impl Default for BpfTrampolineInjector {
    fn default() -> Self {
        Self::new()
    }
}

impl Default for SharedHotPatcher {
    fn default() -> Self {
        Self::new()
    }
}

impl SharedHotPatcher {
    pub async fn inject_kprobe(
        &self,
        patch_id: &str,
        bytecode: &[u8],
        program_name: &str,
        target_function: &str,
        offset: u64,
    ) -> Result<()> {
        let mut patcher = self.inner.lock().await;
        patcher.inject_kprobe(patch_id, bytecode, program_name, target_function, offset)
    }

    pub async fn inject_uprobe(
        &self,
        patch_id: &str,
        bytecode: &[u8],
        program_name: &str,
        target_binary: &str,
        symbol: &str,
        pid: Option<i32>,
    ) -> Result<()> {
        let mut patcher = self.inner.lock().await;
        patcher.inject_uprobe(patch_id, bytecode, program_name, target_binary, symbol, pid)
    }

    pub async fn inject_freplace(
        &self,
        patch_id: &str,
        bytecode: &[u8],
        program_name: &str,
        target_func_name: &str,
        target_program_name: Option<&str>,
    ) -> Result<()> {
        let mut patcher = self.inner.lock().await;
        patcher.inject_freplace(patch_id, bytecode, program_name, target_func_name, target_program_name)
    }

    pub async fn rollback(&self, patch_id: &str) -> Result<()> {
        let mut patcher = self.inner.lock().await;
        patcher.rollback(patch_id)
    }

    pub async fn rollback_all(&self) -> Result<usize> {
        let mut patcher = self.inner.lock().await;
        patcher.rollback_all()
    }

    pub async fn report_patch_error(&self, patch_id: &str, error_msg: &str) {
        let mut patcher = self.inner.lock().await;
        patcher.report_patch_error(patch_id, error_msg);
    }

    pub async fn auto_health_audit(&self, max_allowed_errors: u32) -> Vec<String> {
        let mut patcher = self.inner.lock().await;
        patcher.auto_health_audit(max_allowed_errors)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_kprobe_injection_and_rollback() {
        let patcher = SharedHotPatcher::new();
        let res = patcher
            .inject_kprobe("patch-kprobe-01", &[], "sys_execve_probe", "sys_execve", 0)
            .await;
        assert!(res.is_ok());

        // Report stability error & auto rollback
        patcher.report_patch_error("patch-kprobe-01", "Page fault in probe execution").await;
        patcher.report_patch_error("patch-kprobe-01", "Page fault in probe execution").await;

        let rolled_back = patcher.auto_health_audit(2).await;
        assert_eq!(rolled_back, vec!["patch-kprobe-01".to_string()]);
    }

    #[tokio::test]
    async fn test_uprobe_injection_and_manual_rollback() {
        let patcher = SharedHotPatcher::new();
        let res = patcher
            .inject_uprobe("patch-uprobe-libc", &[], "malloc_probe", "/usr/lib/libc.so.6", "malloc", None)
            .await;
        assert!(res.is_ok());

        let rollback_res = patcher.rollback("patch-uprobe-libc").await;
        assert!(rollback_res.is_ok());
    }

    #[tokio::test]
    async fn test_freplace_trampoline_injection() -> Result<(), String> {
        let patcher = SharedHotPatcher::new();
        let res = patcher
            .inject_freplace("patch-freplace-01", &[], "faulty_func_patch", "faulty_func", Some("kernel_subsystem"))
            .await;
        assert!(res.is_ok());

        let rolled_back_count = patcher.rollback_all().await.map_err(|e| e.to_string())?;
        assert_eq!(rolled_back_count, 1);
        Ok(())
    }
}
