[package]
name = "athanor-shell-rs"
version = "1.0.0"
edition = "2021"
authors = ["Athanor Forge <forge@athanor.os>"]
description = "Pure Rust native shell for Athanor OS"

[dependencies]
mimalloc = { workspace = true }
gtk4 = { workspace = true }
gtk4-layer-shell = { workspace = true }
glib = { workspace = true }
chrono = "0.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = "0.8"
zbus = { workspace = true }
futures-util = { workspace = true }
notify-rust = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "rt", "sync", "time"] }
notify = "6.1.1"
clap = { workspace = true, features = ["derive"] }
greetd_ipc = "0.10.3"
meval = "0.2"
relm4 = { workspace = true }
landlock = "0.4"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
sha2 = { workspace = true }
hex = { workspace = true }


arc-swap = "1.6"

# Decoupled domain crates
athanor-dock = { path = "../../athanor-dock/athanor-dock-1.0.0" }

athanor-style = { path = "../../../../system/athanor-style" }
athanor-niri-ipc = { version = "0.1.0", path = "../../athanor-niri-ipc" }


[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"

