[package]
name = "athanor-store-rs"
version = "1.0.0"
edition = "2021"
description = "Athanor OS Universal App Store Daemon (Flatpak/OCI)"

[dependencies]
mimalloc = { workspace = true }
athanor-style = { path = "../../../../system/athanor-style" }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
zbus = { workspace = true, features = ["tokio"] }
pqc_dilithium = { workspace = true }
hex = { workspace = true }





[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
