[package]
name = "athanor-sysmon-ebpf"
version = "1.0.0"
edition = "2021"

[dependencies]
aya = { workspace = true }
tokio = { workspace = true, features = ["full", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bytes = { workspace = true }

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
